#!/bin/bash

FILE="inc/Permission.hpp"
OUTPUT="inc/PermissionList.hpp"

if [[ ! -f "$FILE" ]]; then
    echo "Error: File '$FILE' not found."
    exit 1
fi

> "$OUTPUT"

in_rights=0
in_admin=0

regex='^uint8_t[[:space:]]+([a-zA-Z0-9_]+)[[:space:]]*:[[:space:]]*1+;$'

echo "// AUTO-GENERATED FILE: Do not edit directly." >> "$OUTPUT"
echo "// This file is generated by the build system (perm.sh) and any modifications will be lost." >> "$OUTPUT"
echo "// To make changes, update 'Permission.hpp' and rebuild." >> "$OUTPUT"
echo "" >> "$OUTPUT"

while IFS= read -r line; do
    # Remove leading and trailing whitespace
    line=$(echo "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')

    # Skip empty lines and single-line comments
    if [[ -z "$line" || "$line" =~ ^// || "$line" =~ ^/\* || "$line" =~ ^\*/ ]]; then
        continue
    fi

    # Check if entering Rights struct
    if [[ "$line" == "struct Rights {" ]]; then
        in_rights=1
        continue
    fi

    # Check if exiting Rights struct
    if [[ "$line" == "};" && $in_rights -eq 1 ]]; then
        in_rights=0
        continue
    fi

    # Skip lines if not inside Rights struct
    if [[ $in_rights -eq 0 ]]; then
        continue
    fi

    # Check if entering admin struct
    if [[ "$line" == "struct {" ]]; then
        in_admin=1
        continue
    fi

    # Check if exiting admin struct
    if [[ "$line" == "} admin;" ]]; then
        in_admin=0
        continue
    fi

    # Match field definition using the regex variable
    if [[ "$line" =~ $regex ]]; then
        field_name="${BASH_REMATCH[1]}"
        if [[ $in_admin -eq 1 ]]; then
            echo "SET_PERMISSION_ADMIN($field_name)" >> "$OUTPUT"
        else
            echo "SET_PERMISSION($field_name)" >> "$OUTPUT"
        fi
    fi
done < "$FILE"

echo "#undef SET_PERMISSION" >> "$OUTPUT"
echo "#undef SET_PERMISSION_ADMIN" >> "$OUTPUT"

echo ""
echo "===== Generated code in $OUTPUT ====="
echo ""
cat "$OUTPUT"
echo ""
echo "====================================================="
echo ""
