// AUTO-GENERATED FILE: Do not edit directly.
// This file is generated by the build system (perm.sh) and any modifications will be lost.
// To make changes, update 'inc/Channel.hpp' and rebuild.

SET_PERMISSION(i_inviteOnly)
SET_PERMISSION(k_enableKey)
SET_PERMISSION(c_caca)
SET_PERMISSION_ARGNUM(l_userLimit)
#undef SET_PERMISSION
#undef SET_PERMISSION_ADMIN
#undef SET_PERMISSION_ARGNUM
