// AUTO-GENERATED FILE: Do not edit directly.
// This file is generated by the build system (perm.sh) and any modifications will be lost.
// To make changes, update 'Permission.hpp' and rebuild.

SET_PERMISSION(write)
SET_PERMISSION_ADMIN(mute)
SET_PERMISSION_ADMIN(kick)
SET_PERMISSION_ADMIN(ban)
SET_PERMISSION_ADMIN(invite)
SET_PERMISSION_ADMIN(setPassWord)
SET_PERMISSION_ADMIN(changeChannelVisibility)
SET_PERMISSION_ADMIN(changeChannelName)
SET_PERMISSION_ADMIN(changeGrantable)
SET_PERMISSION_ADMIN(caca)
#undef SET_PERMISSION
#undef SET_PERMISSION_ADMIN
