// AUTO-GENERATED FILE: Do not edit directly.
// This file is generated by the build system (perm.sh) and any modifications will be lost.
// To make changes, update 'inc/Permission.hpp' and rebuild.

SET_PERMISSION(isOperator)
#undef SET_PERMISSION
#undef SET_PERMISSION_ADMIN
#undef SET_PERMISSION_ARGNUM
